changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"

npmAlwaysAuth: false

npmAuthToken: ${GITHUB_PACKAGES_READ_WRITE_TOKEN}

npmPublishAccess: public

npmPublishRegistry: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.1.cjs
