version: 2.1

jobs:
  build_packages:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run: yarn
      - run: yarn workspace @thingco/logger build
      - run: yarn workspace @thingco/authentication test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_packages:
          context: Default
