version: 2.1

jobs:
  build_packages:
    docker:
      image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run: yarn
			- run: FORCE_COLOR=1 yarn workspaces foreach -v --topological-dev --exclude @thingco/shared-frontend-libs-playground run build
			- run: yarn workspace @thingco/authentication test
