version: 2.1

jobs:
  test_packages:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run: yarn
      - run: yarn workspace @thingco/authentication-core test --bail
      - run: yarn workspace @thingco/authentication-react test --bail

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test_packages:
          context: Default
