export const enum AuthState {
	// Session check top-level state:
	CheckingSession = "CheckingSession",
	// Username input top-level state:
	UsernameInput = "UsernameInput",
	// Username input substates:
	AwaitingUsernameInput = "AwaitingUsernameInput",
	ValidatingUsernameInput = "ValidatingUsernameInput",
	InvalidUsername = "InvalidUsername",
	PasswordRetriesExceeded = "PasswordRetriesExceeded",
	ValidUsername = "ValidUsername",
	// OTP input top-level state:
	OTPInput = "OTPInput",
	// OTP input substates:
	AwaitingOtpInput = "AwaitingOtpInput",
	ValidatingOtpInput = "ValidatingOtpInput",
	InvalidOtp = "InvalidOtp",
	ValidOtp = "ValidOtp",

	// Username/Password top-level state:
	UsernamePasswordInput = "UsernamePasswordInput",
	// Username/Password substates:
	AwaitingUsernamePasswordInput = "AwaitingUsernamePasswordInput",
	ValidatingUsernamePasswordInput = "ValidatingUsernamePasswordInput",
	InvalidUsernamePasswordInput = "InvalidUsernamePasswordInput",
	ValidUsernamePasswordInput = "ValidUsernamePasswordInput",
	// Authorised top-level state:
	Authorised = "Authorised",
	// Logging out top-level state:
	LoggingOut = "LoggingOut",
}

/**
 * IDs are autogenerated by XState, but it is useful to
 *
 * a. have one for the root node (this is recommended), and
 * b. add an ID to state nodes that need to be specifically targeted. This is _extremely_
 *    useful, particularly with heirarchical/nested state machines, as it allows you to
 * 	  use `target: "#MyId"` (note the `#` prefix) to jump directly to a specific state node.
 */
export const enum AuthStateId {
	Authenticator = "Authenticator",
	PasswordRetriesExceeded = "PasswordRetriesExceeded",
}

export const enum AuthEventType {
	LOG_OUT = "LOG_OUT",
	SUBMIT_USERNAME = "SUBMIT_USERNAME",
	SUBMIT_OTP = "SUBMIT_OTP",
	SUBMIT_USERNAME_AND_PASSWORD = "SUBMIT_USERNAME_AND_PASSWORD",
}

export const enum AuthAction {
	NetworkReqStarted = "NetworkReqStarted",
	NetworkReqComplete = "NetworkReqComplete",
	UserDetailsReceived = "UserDetailsReceived",
	ClearPassword = "ClearPassword",
	ClearUsername = "ClearUsername",
	ClearUsernamePassword = "ClearUsernamePassword",
	SetPassword = "SetPassword",
	SetUser = "SetUser",
	SetUsername = "SetUsername",
	SetUsernamePassword = "SetUsernamePassword",
	DecrementRetries = "DecrementRetries",
	ResetRetries = "ResetRetries",
}

export const enum AuthCond {
	IsUsingOTPAuth = "IsUsingOTPAuth",
	HasRetriesRemaining = "HasRetriesRemaining",
}

export const enum AuthServices {
	currentSession = "currentSession",
	validateUsernameAndPassword = "validateUsernameAndPassword",
	validateUsername = "validateUsername",
	validateOtp = "validateOtp",
	signOut = "signOut",
}
